export const SET_USERNAME = 'SET_USERNAME';
export const SAVE_GOOGLE_DATA = 'SAVE_GOOGLE_DATA';
export const SAVE_USER_DATA = 'SAVE_USER_DATA';
export const SAVE_ACTIVE_LOCATION = 'SAVE_ACTIVE_LOCATION';
